// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Holder    string    `json:"holder"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"createdAt"`
	Currency  string    `json:"currency"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"accountID"`
	CreatedAt time.Time `json:"createdAt"`
	// amount can be positive or negative
	Amount int64 `json:"amount"`
}

type Txn struct {
	ID            int64     `json:"id"`
	FromAccountID int64     `json:"fromAccountID"`
	ToAccountID   int64     `json:"toAccountID"`
	CreatedAt     time.Time `json:"createdAt"`
	// amount can only be positive
	Amount int64 `json:"amount"`
}
